import { MediaApiError } from "../media/mediaErrorUtils";

export type AuthErrorCode =
  | "AUTH_REQUIRED"
  | "AUTH_INVALID_CREDENTIALS"
  | "AUTH_SESSION_EXPIRED"
  | "AUTH_SESSION_INVALID"
  | "AUTH_SESSION_REVOKED"
  | "AUTH_ACCOUNT_LOCKED"
  | "AUTH_ACCOUNT_DISABLED"
  | "AUTH_PERMISSION_DENIED"
  | "AUTH_PASSWORD_POLICY_FAILED"
  | "AUTH_PASSWORD_INCORRECT"
  | "AUTH_RESET_TOKEN_INVALID"
  | "AUTH_RESET_TOKEN_EXPIRED"
  | "AUTH_RESET_UNAVAILABLE"
  | "AUTH_USER_NOT_FOUND"
  | "AUTH_EMAIL_ALREADY_EXISTS"
  | "AUTH_ROLE_INVALID"
  | "AUTH_ROLE_ASSIGNMENT_DENIED"
  | "AUTH_LAST_SUPER_ADMIN_PROTECTED"
  | "AUTH_RATE_LIMITED"
  | "AUTH_CSRF_INVALID"
  | "AUTH_BOOTSTRAP_NOT_ALLOWED";
  // Member identity errors intentionally use the auth error transport while staying code-distinct.
export type MemberAuthErrorCode =
  | "MEMBER_EMAIL_INVALID"
  | "MEMBER_DISPLAY_NAME_INVALID"
  | "MEMBER_TERMS_REQUIRED"
  | "MEMBER_PASSWORD_INVALID"
  | "MEMBER_EMAIL_EXISTS"
  | "MEMBER_VERIFICATION_INVALID"
  | "MEMBER_VERIFICATION_EXPIRED"
  | "MEMBER_NOT_FOUND"
  | "MEMBER_AUTH_REQUIRED"
  | "MEMBER_SESSION_INVALID"
  | "MEMBER_EMAIL_UNVERIFIED"
  | "MEMBER_ACCOUNT_DISABLED"
  | "MEMBER_ACCOUNT_LOCKED"
  | "MEMBER_RESET_TOKEN_INVALID"
  | "MEMBER_RESET_TOKEN_EXPIRED"
  | "MEMBER_PASSWORD_INCORRECT";

const defaultStatus: Record<AuthErrorCode | MemberAuthErrorCode, number> = {
  AUTH_REQUIRED: 401,
  AUTH_INVALID_CREDENTIALS: 401,
  AUTH_SESSION_EXPIRED: 401,
  AUTH_SESSION_INVALID: 401,
  AUTH_SESSION_REVOKED: 401,
  AUTH_ACCOUNT_LOCKED: 423,
  AUTH_ACCOUNT_DISABLED: 403,
  AUTH_PERMISSION_DENIED: 403,
  AUTH_PASSWORD_POLICY_FAILED: 400,
  AUTH_PASSWORD_INCORRECT: 400,
  AUTH_RESET_TOKEN_INVALID: 400,
  AUTH_RESET_TOKEN_EXPIRED: 400,
  AUTH_RESET_UNAVAILABLE: 409,
  AUTH_USER_NOT_FOUND: 404,
  AUTH_EMAIL_ALREADY_EXISTS: 409,
  AUTH_ROLE_INVALID: 400,
  AUTH_ROLE_ASSIGNMENT_DENIED: 403,
  AUTH_LAST_SUPER_ADMIN_PROTECTED: 409,
  AUTH_RATE_LIMITED: 429,
  AUTH_CSRF_INVALID: 403,
  AUTH_BOOTSTRAP_NOT_ALLOWED: 409,
  MEMBER_EMAIL_INVALID: 400,
  MEMBER_DISPLAY_NAME_INVALID: 400,
  MEMBER_TERMS_REQUIRED: 400,
  MEMBER_PASSWORD_INVALID: 400,
  MEMBER_EMAIL_EXISTS: 409,
  MEMBER_VERIFICATION_INVALID: 400,
  MEMBER_VERIFICATION_EXPIRED: 400,
  MEMBER_NOT_FOUND: 404,
  MEMBER_AUTH_REQUIRED: 401,
  MEMBER_SESSION_INVALID: 401,
  MEMBER_EMAIL_UNVERIFIED: 403,
  MEMBER_ACCOUNT_DISABLED: 403,
  MEMBER_ACCOUNT_LOCKED: 423,
  MEMBER_RESET_TOKEN_INVALID: 400,
  MEMBER_RESET_TOKEN_EXPIRED: 400,
  MEMBER_PASSWORD_INCORRECT: 400,
};

export class AuthApiError extends MediaApiError {
  constructor(code: AuthErrorCode | MemberAuthErrorCode, message: string, status = defaultStatus[code]) {
    super(code as never, message, status, "auth");
  }
}

export const genericInvalidCredentials = () => new AuthApiError("AUTH_INVALID_CREDENTIALS", "Invalid email or password.", 401);
