import type { IncomingMessage, ServerResponse } from "node:http";
import { adminMediaController } from "../controllers/adminMediaController";
import { adminMediaIntakeController } from "../controllers/adminMediaIntakeController";
import { adminMediaProcessingController } from "../controllers/adminMediaProcessingController";
import { adminDatabaseController } from "../controllers/adminDatabaseController";
import { adminPublicationController } from "../controllers/adminPublicationController";
import { adminSystemConfigurationController } from "../controllers/adminSystemConfigurationController";
import { sendJson } from "../middleware/mediaErrorMiddleware";

export const handleAdminMediaRoute = async (request: IncomingMessage, response: ServerResponse, url: URL): Promise<boolean> => {
  const method = request.method ?? "GET";
  const path = url.pathname.replace(/\/+$/, "") || "/";
  if (method === "OPTIONS") {
    sendJson(response, 204, {});
    return true;
  }
  if (method === "GET" && path === "/api/admin/system/configuration/health") return adminSystemConfigurationController.health(request, response).then(() => true);
  if (method === "GET" && path === "/api/admin/system/configuration/validation") return adminSystemConfigurationController.validation(request, response).then(() => true);
  if (method === "GET" && path === "/api/admin/system/database/health") return adminDatabaseController.health(request, response).then(() => true);
  if (method === "POST" && path === "/api/admin/publication") return adminPublicationController.createOperation(request, response).then(() => true);
  if (method === "GET" && path === "/api/admin/publication/health") return adminPublicationController.health(request, response).then(() => true);
  if (method === "GET" && path === "/api/admin/publication/locks") return adminPublicationController.locks(request, response).then(() => true);
  if (method === "POST" && path === "/api/admin/publication/recover-stale") return adminPublicationController.recoverStale(request, response).then(() => true);
  if (method === "GET" && path === "/api/admin/publication/operations") return adminPublicationController.listOperations(request, response, url).then(() => true);
  const publicationOperationMatch = /^\/api\/admin\/publication\/operations\/([^/]+)$/.exec(path);
  if (method === "GET" && publicationOperationMatch) return adminPublicationController.getOperation(request, response, publicationOperationMatch[1]).then(() => true);
  const publicationRetryMatch = /^\/api\/admin\/publication\/operations\/([^/]+)\/retry$/.exec(path);
  if (method === "POST" && publicationRetryMatch) return adminPublicationController.retry(request, response, publicationRetryMatch[1]).then(() => true);
  const publicationRollbackMatch = /^\/api\/admin\/publication\/operations\/([^/]+)\/rollback$/.exec(path);
  if (method === "POST" && publicationRollbackMatch) return adminPublicationController.rollback(request, response, publicationRollbackMatch[1]).then(() => true);
  const publicationCancelMatch = /^\/api\/admin\/publication\/operations\/([^/]+)\/cancel$/.exec(path);
  if (method === "POST" && publicationCancelMatch) return adminPublicationController.cancel(request, response, publicationCancelMatch[1]).then(() => true);
  const publicationReadinessMatch = /^\/api\/admin\/publication\/([^/]+)\/([^/]+)\/readiness$/.exec(path);
  if (method === "GET" && publicationReadinessMatch) return adminPublicationController.readiness(request, response, publicationReadinessMatch[1], publicationReadinessMatch[2]).then(() => true);
  const publicationActionMatch = /^\/api\/admin\/publication\/([^/]+)\/([^/]+)\/(publish|republish|unpublish|archive|restore|rollback)$/.exec(path);
  if (method === "POST" && publicationActionMatch) return adminPublicationController.entityAction(request, response, publicationActionMatch[1], publicationActionMatch[2], publicationActionMatch[3] as never).then(() => true);
  if (method === "GET" && path === "/api/admin/media/processing/jobs") return adminMediaProcessingController.listJobs(request, response, url).then(() => true);
  if (method === "POST" && path === "/api/admin/media/processing/jobs") return adminMediaProcessingController.createJob(request, response).then(() => true);
  if (method === "GET" && path === "/api/admin/media/processing/health") return adminMediaProcessingController.health(request, response).then(() => true);
  if (method === "GET" && path === "/api/admin/media/processing/dead-letter") return adminMediaProcessingController.deadLetter(request, response, url).then(() => true);
  if (method === "GET" && path === "/api/admin/media/processing/recovery") return adminMediaProcessingController.recovery(request, response).then(() => true);
  if (method === "GET" && path === "/api/admin/media/intake/health") return adminMediaIntakeController.health(request, response).then(() => true);
  if (method === "GET" && path === "/api/admin/media/intake/status") return adminMediaIntakeController.status(request, response).then(() => true);
  if (method === "GET" && path === "/api/admin/media/intake/records") return adminMediaIntakeController.records(request, response, url).then(() => true);
  if (method === "POST" && path === "/api/admin/media/intake/scan") return adminMediaIntakeController.scan(request, response).then(() => true);
  if (method === "POST" && path === "/api/admin/media/intake/start") return adminMediaIntakeController.start(request, response).then(() => true);
  if (method === "POST" && path === "/api/admin/media/intake/stop") return adminMediaIntakeController.stop(request, response).then(() => true);
  const processingAssetMatch = /^\/api\/admin\/media\/assets\/([^/]+)\/processing$/.exec(path);
  if (method === "GET" && processingAssetMatch) return adminMediaProcessingController.getAssetSummary(request, response, processingAssetMatch[1]).then(() => true);
  const processingJobMatch = /^\/api\/admin\/media\/processing\/jobs\/([^/]+)$/.exec(path);
  if (method === "GET" && processingJobMatch) return adminMediaProcessingController.getJob(request, response, processingJobMatch[1]).then(() => true);
  const processingRetryMatch = /^\/api\/admin\/media\/processing\/jobs\/([^/]+)\/retry$/.exec(path);
  if (method === "POST" && processingRetryMatch) return adminMediaProcessingController.retryJob(request, response, processingRetryMatch[1]).then(() => true);
  const processingCancelMatch = /^\/api\/admin\/media\/processing\/jobs\/([^/]+)\/cancel$/.exec(path);
  if (method === "POST" && processingCancelMatch) return adminMediaProcessingController.cancelJob(request, response, processingCancelMatch[1]).then(() => true);
  const deadLetterRetryMatch = /^\/api\/admin\/media\/processing\/dead-letter\/([^/]+)\/retry$/.exec(path);
  if (method === "POST" && deadLetterRetryMatch) return adminMediaProcessingController.retryDeadLetter(request, response, deadLetterRetryMatch[1]).then(() => true);
  const recoveryJobMatch = /^\/api\/admin\/media\/processing\/recovery\/([^/]+)$/.exec(path);
  if (method === "POST" && recoveryJobMatch) return adminMediaProcessingController.recoverJob(request, response, recoveryJobMatch[1]).then(() => true);
  const processingQueuePauseMatch = /^\/api\/admin\/media\/processing\/queues\/([^/]+)\/pause$/.exec(path);
  if (method === "POST" && processingQueuePauseMatch) return adminMediaProcessingController.pauseQueue(request, response, processingQueuePauseMatch[1]).then(() => true);
  const processingQueueResumeMatch = /^\/api\/admin\/media\/processing\/queues\/([^/]+)\/resume$/.exec(path);
  if (method === "POST" && processingQueueResumeMatch) return adminMediaProcessingController.resumeQueue(request, response, processingQueueResumeMatch[1]).then(() => true);
  if (method === "POST" && path === "/api/admin/media/direct-upload/sessions") return adminMediaController.createDirectUploadSession(request, response).then(() => true);
  if (method === "GET" && path === "/api/admin/media/direct-upload/sessions") return adminMediaController.listDirectUploadSessions(request, response).then(() => true);
  if (method === "POST" && path === "/api/admin/media/direct-upload/cleanup") return adminMediaController.cleanupDirectUploads(request, response).then(() => true);
  const directSessionMatch = /^\/api\/admin\/media\/direct-upload\/sessions\/([^/]+)$/.exec(path);
  if (method === "GET" && directSessionMatch) return adminMediaController.getDirectUploadSession(request, response, directSessionMatch[1]).then(() => true);
  const directPartsMatch = /^\/api\/admin\/media\/direct-upload\/sessions\/([^/]+)\/parts$/.exec(path);
  if (method === "POST" && directPartsMatch) return adminMediaController.recordDirectUploadPart(request, response, directPartsMatch[1]).then(() => true);
  const directPartUrlMatch = /^\/api\/admin\/media\/direct-upload\/sessions\/([^/]+)\/parts\/(\d+)\/url$/.exec(path);
  if (method === "POST" && directPartUrlMatch) return adminMediaController.directUploadPartUrl(request, response, directPartUrlMatch[1], Number(directPartUrlMatch[2])).then(() => true);
  const directCompleteMatch = /^\/api\/admin\/media\/direct-upload\/sessions\/([^/]+)\/complete$/.exec(path);
  if (method === "POST" && directCompleteMatch) return adminMediaController.completeDirectUpload(request, response, directCompleteMatch[1]).then(() => true);
  const directCancelMatch = /^\/api\/admin\/media\/direct-upload\/sessions\/([^/]+)\/cancel$/.exec(path);
  if (method === "POST" && directCancelMatch) return adminMediaController.cancelDirectUpload(request, response, directCancelMatch[1]).then(() => true);
  const directRetryMatch = /^\/api\/admin\/media\/direct-upload\/sessions\/([^/]+)\/retry$/.exec(path);
  if (method === "POST" && directRetryMatch) return adminMediaController.retryDirectUpload(request, response, directRetryMatch[1]).then(() => true);
  const directRefreshMatch = /^\/api\/admin\/media\/direct-upload\/sessions\/([^/]+)\/refresh$/.exec(path);
  if (method === "POST" && directRefreshMatch) return adminMediaController.refreshDirectUpload(request, response, directRefreshMatch[1]).then(() => true);
  if (method === "POST" && path === "/api/admin/media/upload") return adminMediaController.upload(request, response).then(() => true);
  if (method === "POST" && path === "/api/admin/media/upload/batch") return adminMediaController.uploadBatch(request, response).then(() => true);
  if (method === "GET" && path === "/api/admin/media/uploads") return adminMediaController.listUploads(request, response).then(() => true);
  const uploadMatch = /^\/api\/admin\/media\/uploads\/([^/]+)$/.exec(path);
  if (method === "GET" && uploadMatch) return adminMediaController.getUpload(request, response, uploadMatch[1]).then(() => true);
  const uploadRetryMatch = /^\/api\/admin\/media\/uploads\/([^/]+)\/retry$/.exec(path);
  if (method === "POST" && uploadRetryMatch) return adminMediaController.retryUpload(request, response, uploadRetryMatch[1]).then(() => true);
  const uploadCancelMatch = /^\/api\/admin\/media\/uploads\/([^/]+)\/cancel$/.exec(path);
  if (method === "POST" && uploadCancelMatch) return adminMediaController.cancelUpload(request, response, uploadCancelMatch[1]).then(() => true);
  if (method === "GET" && path === "/api/admin/media/assets") return adminMediaController.listAssets(request, response).then(() => true);
  const assetMatch = /^\/api\/admin\/media\/assets\/([^/]+)$/.exec(path);
  if (method === "GET" && assetMatch) return adminMediaController.getAsset(request, response, assetMatch[1]).then(() => true);
  if (method === "PATCH" && assetMatch) return adminMediaController.patchAsset(request, response, assetMatch[1]).then(() => true);
  if (method === "DELETE" && assetMatch) return adminMediaController.deleteAsset(request, response, assetMatch[1]).then(() => true);
  const assetVersionsMatch = /^\/api\/admin\/media\/assets\/([^/]+)\/versions$/.exec(path);
  if (method === "GET" && assetVersionsMatch) return adminMediaController.getAssetVersions(request, response, assetVersionsMatch[1]).then(() => true);
  const assetReplaceMatch = /^\/api\/admin\/media\/assets\/([^/]+)\/replace$/.exec(path);
  if (method === "POST" && assetReplaceMatch) return adminMediaController.replaceAssetFromStorage(request, response, assetReplaceMatch[1]).then(() => true);
  const assetRollbackMatch = /^\/api\/admin\/media\/assets\/([^/]+)\/versions\/([^/]+)\/rollback$/.exec(path);
  if (method === "POST" && assetRollbackMatch) return adminMediaController.rollbackAssetVersion(request, response, assetRollbackMatch[1], assetRollbackMatch[2]).then(() => true);
  const assetVersionArchiveMatch = /^\/api\/admin\/media\/assets\/([^/]+)\/versions\/([^/]+)\/archive$/.exec(path);
  if (method === "POST" && assetVersionArchiveMatch) return adminMediaController.archiveAssetVersion(request, response, assetVersionArchiveMatch[1], assetVersionArchiveMatch[2]).then(() => true);
  const assetLinkMatch = /^\/api\/admin\/media\/assets\/([^/]+)\/links$/.exec(path);
  if (method === "POST" && assetLinkMatch) return adminMediaController.linkAsset(request, response, assetLinkMatch[1]).then(() => true);
  const assetDependenciesMatch = /^\/api\/admin\/media\/assets\/([^/]+)\/dependencies$/.exec(path);
  if (method === "GET" && assetDependenciesMatch) return adminMediaController.getAssetDependencies(request, response, assetDependenciesMatch[1]).then(() => true);
  const generateAudioPreviewMatch = /^\/api\/admin\/media\/assets\/([^/]+)\/generate-audio-preview$/.exec(path);
  if (method === "POST" && generateAudioPreviewMatch) return adminMediaController.generateAudioPreview(request, response, generateAudioPreviewMatch[1]).then(() => true);
  const detachLinkMatch = /^\/api\/admin\/media\/links\/([^/]+)\/detach$/.exec(path);
  if (method === "POST" && detachLinkMatch) return adminMediaController.detachAssetLink(request, response, detachLinkMatch[1]).then(() => true);
  const archiveMatch = /^\/api\/admin\/media\/assets\/([^/]+)\/archive$/.exec(path);
  if (method === "POST" && archiveMatch) return adminMediaController.archiveAsset(request, response, archiveMatch[1]).then(() => true);
  const restoreMatch = /^\/api\/admin\/media\/assets\/([^/]+)\/restore$/.exec(path);
  if (method === "POST" && restoreMatch) return adminMediaController.restoreAsset(request, response, restoreMatch[1]).then(() => true);
  if (method === "GET" && path === "/api/admin/media/storage/health") return adminMediaController.storageHealth(request, response).then(() => true);
  if (method === "GET" && path === "/api/admin/media/storage/reconciliation") return adminMediaController.storageReconciliation(request, response).then(() => true);
  if (method === "GET" && path === "/api/admin/media/storage/full-song-privacy") return adminMediaController.verifyFullSongPrivacy(request, response).then(() => true);
  if ((method === "GET" || method === "POST") && path === "/api/admin/media/storage/signed-url") return adminMediaController.signedUrl(request, response, url).then(() => true);
  if (method === "GET" && path === "/api/admin/media/storage") return adminMediaController.listStorageObjects(request, response).then(() => true);
  const storageObjectContentMatch = /^\/api\/admin\/media\/storage\/objects\/([^/]+)\/content$/.exec(path);
  if ((method === "GET" || method === "HEAD") && storageObjectContentMatch) return adminMediaController.streamStorageObject(request, response, storageObjectContentMatch[1]).then(() => true);
  const storageObjectMatch = /^\/api\/admin\/media\/storage\/objects\/([^/]+)$/.exec(path);
  if (method === "HEAD" && storageObjectMatch) return adminMediaController.fileExists(request, response, storageObjectMatch[1]).then(() => true);
  if (method === "GET" && storageObjectMatch) return adminMediaController.fileExists(request, response, storageObjectMatch[1]).then(() => true);
  if (method === "DELETE" && storageObjectMatch) return adminMediaController.deleteStorageObject(request, response, storageObjectMatch[1]).then(() => true);
  const verifyAssetStorageMatch = /^\/api\/admin\/media\/assets\/([^/]+)\/storage\/verify$/.exec(path);
  if (method === "GET" && verifyAssetStorageMatch) return adminMediaController.verifyAssetStorage(request, response, verifyAssetStorageMatch[1]).then(() => true);
  const demoteAssetMatch = /^\/api\/admin\/media\/assets\/([^/]+)\/demote-private$/.exec(path);
  if (method === "POST" && demoteAssetMatch) return adminMediaController.demoteAsset(request, response, demoteAssetMatch[1]).then(() => true);
  const promoteMatch = /^\/api\/admin\/media\/storage\/objects\/([^/]+)\/promote-public$/.exec(path);
  if (method === "POST" && promoteMatch) return adminMediaController.promoteStorageObject(request, response, promoteMatch[1]).then(() => true);
  const demoteMatch = /^\/api\/admin\/media\/storage\/objects\/([^/]+)\/demote-private$/.exec(path);
  if (method === "POST" && demoteMatch) return adminMediaController.demoteStorageObject(request, response, demoteMatch[1]).then(() => true);
  return false;
};
