import { getBackendConfig } from "./backendConfig";

const config = getBackendConfig();

export const mediaBackendConfig = {
  port: config.server.port,
  host: config.server.host,
  provider: config.storage.provider,
  endpoint: config.storage.endpoint,
  bucket: config.storage.bucket,
  region: config.storage.region,
  accessKeyId: config.storage.accessKeyId,
  secretAccessKey: config.storage.secretAccessKey,
  forcePathStyle: config.storage.forcePathStyle,
  cdnEnabled: config.cdn.enabled,
  cdnBaseUrl: config.cdn.baseUrl,
  publicBaseUrl: config.storage.publicBaseUrl || "/uploads/media/public",
  privatePrefix: config.storage.privatePrefix,
  publicPrefix: config.storage.publicPrefix,
  uploadRoot: config.storage.localRoot,
  dataRoot: config.storage.dataRoot,
  maxImageBytes: config.uploads.maxImageBytes,
  maxAudioPreviewBytes: config.uploads.maxAudioPreviewBytes,
  maxFullSongBytes: config.uploads.maxFullSongBytes,
  directUploadMinFileSizeBytes: config.uploads.directUploadThresholdBytes,
  directUploadPartSizeBytes: config.uploads.directUploadPartSizeBytes,
  directUploadMaxParts: config.uploads.directUploadMaxParts,
  directUploadExpirationSeconds: config.uploads.directUploadSessionExpirationSeconds,
  directUploadMaxRetriesPerPart: config.uploads.maxRetries,
  directUploadParallelParts: config.uploads.directUploadParallelParts,
  mediaQueueRedisUrl: config.redis.url,
  mediaQueuePrefix: config.redis.prefix,
  mediaImageWorkerConcurrency: config.processing.imageConcurrency,
  mediaAudioWorkerConcurrency: config.processing.audioConcurrency,
  mediaStorageWorkerConcurrency: config.processing.storageConcurrency,
  mediaPublicationWorkerConcurrency: config.processing.publicationConcurrency,
  mediaPublicationMaxAttempts: config.publication.maxAttempts,
  mediaPublicationBackoffMs: config.publication.backoffMs,
  mediaPublicationTimeoutMs: config.publication.operationTimeoutMs,
  mediaJobMaxAttempts: config.processing.maxAttempts,
  mediaJobBackoffMs: config.processing.backoffMs,
  mediaJobRemoveCompletedAfter: 86400,
  mediaJobRemoveFailedAfter: 604800,
  mediaWorkersEnabled: config.processing.workersEnabled,
  mediaWorkerShutdownTimeoutMs: config.processing.shutdownTimeoutMs,
  mediaAudioTranscodeEnabled: config.processing.transcodingEnabled,
  mediaAudioPreviewBitrate: process.env.MEDIA_AUDIO_PREVIEW_BITRATE?.trim() || "128k",
  mediaAudioAacBitrate: process.env.MEDIA_AUDIO_AAC_BITRATE?.trim() || "128k",
  signedUrlExpirationSeconds: config.storage.signedUrlExpirationSeconds,
  maxSignedUrlExpirationSeconds: config.security.signedUrlMaxExpirationSeconds,
  devAdminToken: config.auth.legacyDevAdminToken || "",
  allowMockFallback: config.storage.allowProductionMockFallback || !config.app.isProduction,
};

export type MediaBackendConfig = typeof mediaBackendConfig;
