import type { ConsentCategory } from "../../models/analytics/ConsentPolicyModel";

export const analyticsEventCatalog = {
  page_view: { category: "analytics", properties: ["routePattern", "isNotFound", "pageTitle"] },
  navigation_clicked: { category: "analytics", properties: ["linkType", "destinationCategory", "sourceContext", "position"] },
  footer_link_clicked: { category: "analytics", properties: ["linkType", "destinationCategory", "sourceContext", "position"] },
  cta_clicked: { category: "analytics", properties: ["label", "destinationCategory", "sourceContext", "position"] },
  external_platform_clicked: { category: "analytics", properties: ["platform", "sourceContext", "entityType", "entityId"] },
  artist_viewed: { category: "analytics", properties: ["artistId", "artistSlug", "sourceContext"] },
  release_viewed: { category: "analytics", properties: ["releaseId", "artistId", "sourceContext"] },
  gallery_item_viewed: { category: "analytics", properties: ["galleryItemId", "sourceType", "openContext", "position"] },
  audio_preview_play_requested: { category: "analytics", properties: ["releaseId", "artistId", "sourceContext"] },
  audio_preview_started: { category: "analytics", properties: ["releaseId", "artistId", "sourceContext"] },
  audio_preview_paused: { category: "analytics", properties: ["releaseId", "artistId", "positionBucket"] },
  audio_preview_resumed: { category: "analytics", properties: ["releaseId", "artistId", "positionBucket"] },
  audio_preview_seeked: { category: "analytics", properties: ["releaseId", "artistId", "positionBucket"] },
  audio_preview_completed: { category: "analytics", properties: ["releaseId", "artistId"] },
  audio_preview_error: { category: "analytics", properties: ["releaseId", "artistId", "errorCategory"] },
  search_submitted: { category: "analytics", properties: ["queryLength", "resultCount", "zeroResults", "entityTypeFilter", "filterNames", "sort"] },
  search_results_viewed: { category: "analytics", properties: ["queryLength", "resultCount", "zeroResults"] },
  search_zero_results: { category: "analytics", properties: ["queryLength", "entityTypeFilter"] },
  search_result_clicked: { category: "analytics", properties: ["selectedResultType", "selectedResultPosition"] },
  search_filter_applied: { category: "analytics", properties: ["filterNames", "resultCount"] },
  browse_mode_viewed: { category: "analytics", properties: ["genre", "tag", "resultCount"] },
  contact_form_submitted: { category: "analytics", properties: ["formLocation", "formVariant"] },
  contact_form_accepted: { category: "analytics", properties: ["formLocation", "formVariant", "result"] },
  contact_form_error: { category: "analytics", properties: ["formLocation", "errorCategory"] },
  newsletter_signup_submitted: { category: "analytics", properties: ["formLocation", "formVariant"] },
  newsletter_signup_accepted: { category: "analytics", properties: ["formLocation", "formVariant", "result"] },
  newsletter_confirmation_completed: { category: "analytics", properties: ["result"] },
  newsletter_unsubscribed: { category: "analytics", properties: ["result"] },
  consent_banner_viewed: { category: "necessary", properties: ["policyVersion", "gpcApplied"] },
  consent_accepted_all: { category: "necessary", properties: ["policyVersion", "choiceCategories", "gpcApplied"] },
  consent_rejected_optional: { category: "necessary", properties: ["policyVersion", "choiceCategories", "gpcApplied"] },
  consent_preferences_saved: { category: "necessary", properties: ["policyVersion", "choiceCategories", "gpcApplied"] },
  consent_withdrawn: { category: "necessary", properties: ["policyVersion", "choiceCategories"] },
  public_client_error: { category: "analytics", properties: ["errorCategory", "routePattern"] },
  web_vital_reported: { category: "analytics", properties: ["metric", "value", "rating", "routeKey"] },
} as const satisfies Record<string, { category: ConsentCategory; properties: readonly string[] }>;

export type AnalyticsEventName = keyof typeof analyticsEventCatalog;
